# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build Next.js App
      run: npm run build

    - name: Deploy to EC2
      uses: appleboy/scp-action@master  # THIS IS TO COPY THE FILES TO EC2
      with:
        host: ${{ secrets.EC2_HOST }} # your ec2 ip addess
        username: ${{ secrets.EC2_USER }} # your ec2 machine whether ubuntu or centos
        key: ${{ secrets.PRIVATE_SSH_KEY }} # your ec2 private ssh key 
        port: ${{ secrets.EC2_PORT }} # 22 is default port to connect anything using ssh
        source: "."  # what to copy
        target: "~/nextjs-app"

    - name: SSH and restart PM2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          cd ~/nextjs-app
          npm install
          npm run build
          pm2 start npm --name "nextjs-app" -- start || pm2 restart "nextjs-app"
